INSERT INTO STATION_DETAILS (ID, NAME, ZONES) VALUES (1, 'Hamilton', 'ZONE_1');
INSERT INTO STATION_DETAILS (ID, NAME, ZONES) VALUES (2, 'Thunder Bay', 'ZONE_1,ZONE_2');
INSERT INTO STATION_DETAILS (ID, NAME, ZONES) VALUES (3, 'Dryden', 'ZONE_3');
INSERT INTO STATION_DETAILS (ID, NAME, ZONES) VALUES (4, 'Slate Falls', 'ZONE_2');


INSERT INTO CARD_DETAILS (ID, CARD_NUMBER, ISSUED_PLACE, BALANCE, ISSUED_TIME, UPDATED_TIME)
VALUES (1, '2022011', 'Dubai', 100, null, null);
INSERT INTO CARD_DETAILS (ID, CARD_NUMBER, ISSUED_PLACE, BALANCE, ISSUED_TIME, UPDATED_TIME)
VALUES (2, '2022012', 'Dubai', 3.2, null, null);
INSERT INTO CARD_DETAILS (ID, CARD_NUMBER, ISSUED_PLACE, BALANCE, ISSUED_TIME, UPDATED_TIME)
VALUES (3, '2022013', 'Dubai', 1, null, null);

-- select * from TOUCH_POINT_DETAILS;
-- select * from CARD_DETAILS;